name: Validate Java solution
on:
  workflow_dispatch:
  pull_request:
jobs:
  validate-java:
    name: Validate Java solution
    runs-on: ubuntu-latest
    container: maven:3-eclipse-temurin-21
    steps:
      - name: Checkout code
        uses: actions/checkout@v4     
      - name: Check Java compiler version
        run: javac --version
      - name: Check Maven version
        run: mvn --version
      - name: Compile Java project
        run: mvn compile
        working-directory: ./src/web
      - name: Package Java project
        run: mvn package
        working-directory: ./src/web
